version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=goals
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=mysql://root:123456@mysql:3306/goals?schema=public
    ports:
      - "4000:4000"
    depends_on:
      - mysql
      - frontend
      
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost
      - VITE_API_PORT=4000

volumes:
  mysql_data: